### PR TITLE
Implement search api

### LINKED ISSUE #46: The path of a URI with an authority must start with a slash "/" or be empty
Hi, I got InvalidArgumentException in Uri.php line 693:
The path of a URI with an authority must start with a slash "/" or be empty

This is my code: 
```
        \Crew\Unsplash\HttpClient::init([
            'applicationId' => 'appId'
        ]);

        $photos = \Crew\Unsplash\Photo::all();

        var_dump($photos);
```

This is composer.json:
```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "crewlabs/unsplash": "^2.2",
        "guzzlehttp/guzzle": "^6.2"
    },
```

PHP -v:
`PHP 7.0.9 (cli) (built: Aug 26 2016 06:17:04) ( NTS )`

And the error stack:
```
in Uri.php line 693
at Uri->validateState() in Uri.php line 471
at Uri->withHost('api.unsplash.com') in HttpClient.php line 140
at HttpClient->Crew\Unsplash\{closure}(object(Request)) in Middleware.php line 233
at Middleware::GuzzleHttp\{closure}(object(Request), array('synchronous' => true, 'handler' => object(HandlerStack), 'allow_redirects' => array('max' => '5', 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false)) in Middleware.php line 233
at Middleware::GuzzleHttp\{closure}(object(Request), array('synchronous' => true, 'handler' => object(HandlerStack), 'allow_redirects' => array('max' => '5', 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false)) in HandlerStack.php line 67
at HandlerStack->__invoke(object(Request), array('synchronous' => true, 'handler' => object(HandlerStack), 'allow_redirects' => array('max' => '5', 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false)) in Client.php line 275
at Client->transfer(object(Request), array('synchronous' => true, 'handler' => object(HandlerStack), 'allow_redirects' => array('max' => '5', 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false)) in Client.php line 96
at Client->sendAsync(object(Request), array('query' => array('page' => '1', 'per_page' => '10'), 'synchronous' => true, 'handler' => object(HandlerStack), 'allow_redirects' => array('max' => '5', 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false, '_conditional' => array('User-Agent' => 'GuzzleHttp/6.2.1 curl/7.45.0 PHP/7.0.9'))) in Client.php line 104
at Client->send(object(Request), array('query' => array('page' => '1', 'per_page' => '10'), 'synchronous' => true)) in HttpClient.php line 111
at HttpClient->send('get', array('photos', array('query' => array('page' => '1', 'per_page' => '10')))) in Endpoint.php line 74
at Endpoint::__callStatic('get', array('photos', array('query' => array('page' => '1', 'per_page' => '10')))) in Photo.php line 32
at Photo::all() in UtilController.php line 23
at UtilController->getFreeImages(object(Request))
```

Is my implementation wrong?

### PR DESCRIPTION
**Pull request by treeleaf**
Implements the search API:

- all
- collections
- photos
- users

Closes #46

### CODE REVIEW

**Comment by lukechesser** [comment]
@treeleaf nice thanks for contributing! Could you add quick documentation to the README as well?

Similarly, the search.yml files for the VCR tests, those need to be committed too I think

**Comment by aaronklaassen** [comment]
@lukechesser This lib suffers from [a similar problem to the one the ruby lib does](https://github.com/unsplash/unsplash_rb/issues/38). I'll take care of it.

**Comment by aaronklaassen** [comment]
Update: @treeleaf I added a VCR cassette with useful results (#50). You can merge master into your branch here and run your tests against it. If they're green then we're good to go. :+1:

**Comment by treeleaf** [comment]
@aaronklaassen I have merged the master branch with the VCR cassette into the pull request and fixed the tests. I have also refactored my code a bit: Search always returns a PageResult object, where you can either access the results as a plain array (getResults) or you can get an ArrayObject implementation from the pageResult.

**Comment by aaronklaassen** [comment]
Perfect, thanks @treeleaf  :+1:

**Pull request merged**
