### PR TITLE
Depend on stable package

### LINKED ISSUE #76: 2.4 requires packages of state dev-master
The first problem is that I cannot update without changing the [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability).

The second problem is that every download of this repo will potentially result in a different version of that dev-master library. That is because libraries do not utilize a lock-file.

Error breakdown on my project:

```
$ composer update crewlabs/unsplash
Loading composer repositories with package information
Updating dependencies (including require-dev)                                  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crewlabs/unsplash ^2.4 -> satisfiable by crewlabs/unsplash[2.4.0].
    - crewlabs/unsplash 2.4.0 requires hughbertd/oauth2-unsplash dev-master -> satisfiable by hughbertd/oauth2-unsplash[dev-master] but these conflict with your requirements or minimum-stability.
```

I'll stick on 2.3 for now :). Thanks for the lib!

### PR DESCRIPTION
**Pull request by roelvanduijnhoven**
This PR depends on https://github.com/unsplash/unsplash-php/pull/77

This will resolve #76 by depending on a stable version.

Oh. And releasing a new version of this library afterwards would help!

### CODE REVIEW

**Comment by lukechesser** [comment]
@roelvanduijnhoven if you want, we could pluck `a5163bd` from this and merge it in. Otherwise I'll create a new PR with just that change

**Comment by roelvanduijnhoven** [comment]
> @roelvanduijnhoven if you want, we could pluck a5163bd from this and merge it in.

Yes; sound great :clap:!

**Comment by GigaMick** [comment]
I have just tried to install this and getting the following

```
- crewlabs/unsplash 2.4.0 requires hughbertd/oauth2-unsplash dev-master -> satisfiable by hughbertd/oauth2-unsplash[dev-master] but these conflict with your requirements or minimum-stability.
```

**Comment by aaronklaassen** [comment]
Closing this in favor of #79.

**Pull request closed without merging**
