### PR TITLE
Added order_by parameter for retrieving photos

### PR DESCRIPTION
**Pull request by HughbertD**
~Will create a separate issue for this should it turn out to be an actual issue~

~When trying to add order_by parameter, its difficult to write a test for, since photos don't seem to actually follow the order_by:~

~e.g. `order_by=latest`: photos aren't ordered by their `created_at` or `modified_at` dates, (though `order_by=latest` and `order_by=oldest` will give back different results)~

As per comment chain below I've dropped the failing test and stopped asserting the order these come back in, instead just checking the number or photos is correct.

### CODE REVIEW

**Comment by lukechesser** [comment]
Well hello sir :)

**Comment by taduuda** [comment]
Photos under unsplash.com/new are ordered by the date they were added to that "list" as far as I know. I wrote about why that is somewhat difficult to handle [here](https://medium.com/@taduuda/i-really-do-love-unsplash-but-bf8788425532).

I'm not entirely sure how the "order_by" parameter behaves on other parts of the site, e.g. a user's photos.

**Comment by lukechesser** [comment]
@taduuda we actually _just_ updated that in the last two weeks to be based on when they're approved by our team, so all photos should appear in order now :)

**Comment by taduuda** [comment]
@lukechesser Just realized my earlier comment is kinda backwards: Said how would like it to be yet calling it difficult to handle. So to be clear: I was trying to say that the old way it was made it difficult to handle. Really appreciate the change!

**Comment by aaronklaassen** [comment]
@taduuda @lukechesser Yeah I talked to @HughbertD about this - basically that you're right there isn't sufficient data in the API response to check that the photos you are getting are the correct ones/in the right order.

But that's fine, since checking which photos you have isn't really this lib's job. Here (and with `unsplash_rb`), my approach has been more to test that the wrapper is doing its job: Are we sending the correct params? Did we parse the response json? Did I get a list of `Photo` objects? Is there the right number of them? etc

Whether or not those the *correct* photos is beside the point, since if they're wrong that's Unsplash API's fault, not `unsplash-php`'s, you know?

**Pull request merged**
