### PR TITLE
Allow newer versions of league/oauth2-client.

### LINKED ISSUE #60: Update to `league/oauth2-client` ^2
Would be good to utilize the latest major branch of `league/oauth2-client` to avoid dependency issues with other packages.

### PR DESCRIPTION
**Pull request by aaronklaassen**
*Actually* closes #60.

@paulm17 could I take you up on your offer to sanity-check this? I don't work in PHP very often so I want to make sure it works for the folks who do. 😄

### CODE REVIEW

**Comment by paulm17** [comment]
Not sure about it being ">=1.4.2".  But hey, we can try it.  Can always do another pull request right?

Apply it and then I can test it for you.

**Comment by aaronklaassen** [comment]
@paulm17 Yeah it worked for me with a `composer upgrade league/oauth2-client`. I made it a `>=` because I'd prefer to keep this a small point-release. Fewer breakages then better.

**Comment by paulm17** [comment]
Unfortunately, it's not working for me.  Maybe I am doing something wrong?

Your requirements could not be resolved to an installable set of packages.

    Problem 1
    - Installation request for crewlabs/unsplash 2.3.3 -> satisfiable by crewlabs/unsplash[2.3.3].
    - crewlabs/unsplash 2.3.3 requires league/oauth2-client 1.4.2 -> satisfiable by league/oauth2-client[1.4.2] but these conflict with your requirements or minimum-stability.

Here is my composer.json

    {
        "require": {
            "abraham/twitteroauth": "0.7.1",
            "braintree/braintree_php": "3.20.0",
            "crewlabs/unsplash": "2.3.3",
            "dirkgroenen/pinterest-api-php": "0.2.11",
            "eventviva/php-image-resize": "1.5.*",
            "facebook/graph-sdk": "5.4.2",
            "facebook/php-ads-sdk": "2.8.*",
            "google/apiclient": "~2.0",
            "haridarshan/instagram-php": "2.2.2",
            "hashids/hashids": "2.0.3",
            "ksubileau/color-thief-php": "1.3.0",
            "league/color-extractor": "0.3.*",
            "league/oauth2-client": "^2",
            "league/oauth2-google": "*",
            "league/oauth2-instagram": "*",
            "league/oauth2-linkedin": "*",        
            "nmred/kafka-php": "0.1.*",
            "pelago/emogrifier": "1.1.0",
            "php-amqplib/php-amqplib": ">=2.6.1",
            "rfreebern/giphy-php": "dev-master",
            "rtheunissen/oauth2-reddit": "2.0.2",
            "sabberworm/php-css-parser": "*",
            "stevenmaguire/oauth2-paypal": "*",
            "sunra/php-simple-html-dom-parser": "1.5.2",
            "vimeo/vimeo-api": "1.2.6",
            "zoonman/pixabay-php-api": "*"
        }
    }

**Comment by aaronklaassen** [comment]
What did you run to get this? `composer install`? Or `upgrade`?

**Comment by paulm17** [comment]
upgrade

**Comment by aaronklaassen** [comment]
I didn't tag this as a new release yet - are you still on the `2.3.3` from the other day?

**Comment by paulm17** [comment]
It just be.  I don't know how to use another source.  I'll wait for you to tag it then :)

**Comment by aaronklaassen** [comment]
@paulm17 `2.3.4-pre1`

**Comment by paulm17** [comment]
Sorry, it's still not working.

    [UnexpectedValueException]
    Could not parse version constraint 2.3.4-pre: Invalid version string "2.3.4-pre"

I have this:  
    "crewlabs/unsplash": "2.3.4-pre",

**Comment by paulm17** [comment]
Update.

So I tried:

    "crewlabs/unsplash": "dev-master#2.3.4-pre1",

I get:

	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Installation request for crewlabs/unsplash dev-master#2.3.4-pre1 -> satisfiable by crewlabs/unsplash[dev-master].
	    - crewlabs/unsplash dev-master requires hughbertd/oauth2-unsplash dev-master -> satisfiable by hughbertd/oauth2-unsplash[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by paulm17** [comment]
Alright, I have it working now:

	"crewlabs/unsplash": "dev-master",
        "hughbertd/oauth2-unsplash": "dev-master",        
         "league/oauth2-client": "^2"

Seems I had to add the line for hughbertd/oauth2-unsplash.

**Pull request merged**
